version: 2
updates:
  - package-ecosystem: "docker-compose"
    directory: "/infra/ec2-stage"
    schedule:
      interval: "daily"
    
    groups:
      # Group 1: Minor and Patch updates (The "Safe" PR)
      minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

      # Group 2: Major updates (The "Review Carefully" PR)
      major-upgrades:
        patterns:
          - "*"
        update-types:
          - "major"